name: Postman API Test

on:
  push:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run collection/postman_collection.json \
          -e environment/postman_environment.json
